config/routes.rb
Rails.application.routes.draw do
  get 'categories/show'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :packets, only: [:new, :create, :index, :show, :destroy] do
    resources :packet_ratings, only: [:create] # upvote
    resources :project_packets, only: [:create]
    resources :packet_tools, only: [:create]
    resources :chatrooms, only: [:create]
  end
  resources :chatrooms, only: [:show, :destroy] do
    resources :messages, only: [:create]
  end

  resources :users, only: [:show]
  resources :projects, only: [:new, :create, :show, :destroy]
  resources :categories, only: [:show]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :projects, dependent: :destroy
  has_many :packets
  has_many :project_packets, through: :projects, source: :packet
  has_many :packet_ratings
  has_many :chatroom_users
  has_many :chatrooms, through: :chatroom_users
  has_one_attached :photo
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @sample_image = ["paint.jpg", "hanging-bulbs.jpg", "interior.jpg", "interior2.jpg", "interior3.jpg", "interior4.jpg", "garden.jpg"]
    @chatrooms = Chatroom.joins(:chatroom_users).where(chatroom_users:{user_id: current_user.id})
    @started_chatrooms = @user.chatrooms.select { |chatroom| chatroom.packet.user != @user }
    @packet_chatrooms = @user.chatrooms.select { |chatroom| chatroom.packet.user == @user }
  end
end

app/views/users/show.html.erb
<div class="user-show-banner">
  <div class="user-show-avatar">
    <% if @user.photo.attached? %>
      <%= cl_image_tag @user.photo.key, class: "user-show-avatar-img" %>
    <% end %>
  </div>
  <% if @user == current_user %>
    <div class="user-options">
      <ul class="nav nav-tabs justify-content-end list-inline tabs-underlined">
        <li class="mx-3 my-3"><a class="tab-underlined" data-toggle="tab" href="#uploads"> Home </a></li>
        <li class="mx-3 my-3"><a class="tab-underlined" data-toggle="tab" href="#messages">Messages</a></li>
        <li class="mx-3 my-3"><a class="tab-underlined" data-toggle="tab" href="#projects"> Your Projects</a></li>
        <li class="mx-3 my-3"><a class="tab-underlined" data-toggle="tab" href="#settings">Account Settings</a></li>
      </ul>
    </div>
  <% else %>
  <div class="user-options">
    <ul class="nav nav-tabs justify-content-end list-inline tabs-underlined">
      <li class="mx-3 my-3"><a class="tab-underlined" data-toggle="tab" href="#uploads"> <%= @user.username%>'s DIY Uploads</a></li>
    </ul>
  </div>
  <% end %>
</div>

<div class= "user-page mx-3 my-3 d-flex">
  <div class="user-info-box w-15 align-items-center">
    <div class = "user-details d-flex justify-content-around ">
      <h3><%= @user.username %></h3>
    </div>
    <div class="text-center">
      <strong><p>Details:<p></strong>
      <p><%=@user.email %></p>
      <strong><p>Lessons Shared:<p></strong>
      <p><%= pluralize @user.packets.size, "lessons" %></p>
      <strong><p>Projects Started:<p></strong>
      <p><%= pluralize @user.projects.size, "projects" %></p>
      <p></p>
    </div>
  </div>
  <div class="d-flex justify-content-center p-4 user-tab-content">
    <div class="tab-content">
      <div id="messages" class="tab-pane fade">
        <div class="chatroom-container border border-success p-2">
          <% if @packet_chatrooms.empty? %>
             <h3 class="text-center">
               No messages yet!
             </h3>
           <% else %>
               <div class="d-flex justify-content-center">
                 <h3 class="mb-3">
                   Messages About Your Lessons
                 </h3>
               </div>
               <div class="card-grid">
                 <%  @packet_chatrooms.each do |chatroom| %>
                   <div class="notification">
                     <div class="img">
                       <%= cl_image_tag chatroom.packet.photos.first.key, width: 150, height: 100 %>
                     </div>
                      <div class="notification-content mx-2">
                        <h2><small><%= chatroom.created_at.strftime("%a %b %e at %l:%M%p") %></small></h2>
                        <h2><strong><%= chatroom.packet.title %></strong> with <%= chatroom.packet.user.username %></h2>
                      </div>
                      <div class="notification-actions">
                        <%= link_to chatroom_path(chatroom) do %>
                          Reply <i class="far fa-envelope-open"></i>
                        <% end %>
                        <%= link_to chatroom_path(chatroom), data: { confirm: "Are you sure?" }, method: :delete do %>
                          Delete<i class="far fa-trash-alt"></i>
                        <% end %>
                      </div>
                    </div>
                 <% end %>
               </div>
            <% end %>
          </div>
         <div class="chatroom-container border border-success mt-3 p-2">
           <div class="card-grid">
            <% if @started_chatrooms.empty? %>
              <h3 class="text-center p-1"><i class="fas fa-envelope"></i></h3>
            <% else %>
              <h3 class="text-center">Messages to DI-WISE Users</h3>
            <% end %>
             <% @started_chatrooms.each do |chatroom| %>
               <div class="notification">
                <div class="img">
                  <%= cl_image_tag chatroom.packet.photos.first.key, width: 150, height: 100 %>
                </div>
                 <div class="notification-content mx-2">
                   <h2><small><%= chatroom.created_at.strftime("%a %b %e at %l:%M%p") %></small></h2>
                   <h2><strong><%= chatroom.packet.title %></strong> with <%= chatroom.packet.user.username %></h2>
                 </div>
                 <div class="notification-actions">
                   <%= link_to chatroom_path(chatroom) do %>
                     Reply <i class="far fa-envelope-open"></i>
                   <% end %>
                   <%= link_to chatroom_path(chatroom), data: { confirm: "Are you sure?" }, method: :delete do %>
                     Delete<i class="far fa-trash-alt"></i>
                   <% end %>
                 </div>
               </div>
             <% end %>
           </div>
         </div>
      </div>
      <div id="uploads" class="tab-pane fade show active">
        <% if @user ==current_user %>
          <div class="container uploads-container d-flex justify-content-between mb-2 ">
            <%= link_to "+Upload a lesson!", new_packet_path, class: "btn btn-primary btn-md btn-rounded btn-open-card text-center"%>
            <h2>Welcome back, <%= @user.username%>!</h2>
          </div>
        <% else %>
          <h2 > <%=@user.username%>'s Profile </h2>
        <% end %>  
      
        <div class = "d-flex container justify-content-center">
          <% if @user.packets.exists? %>
            <% if @user==current_user %>
                <h2 class="text-center mb-5"> Here are your lesson uploads:</h2>
            <% end %>
          <% else %>
            <% if @user==current_user %>
              <h2>No lessons to show</h2>
            <% else %>
              <h3><%= @user.username %> has not uploaded any lessons!</h3>
            <% end %>
          <% end %>
        </div>
        <div class="cards">
          <% @user.packets.each do |packet| %>
            <div class="card diwise-card">
            <%= link_to packet_path(packet) do %>
            <div class ="px-3 pt-3 mt-2">
              <% if packet.youtube_url.present? %>
                <iframe height='250px' class = "w-100 "src="http://www.youtube.com/embed/<%= packet.youtube_url %>"></iframe>
              <% elsif packet.photos.any? %>
                <%= cl_image_tag packet.photos.first.key, class: "card-img-top w-100" %>
              <% end %>
            </div>
            <h5 class="card-title px-3 my-3 packet-title"><%= packet.title %></h5>
            <p class= "card-text px-3 packet-title"><%= packet.category&.name %></p>
          <% end %>
          <div class=" d-flex container container-rating align-items-center justify-content-center" id="packet-<%= packet.id %>">
          <%= packet.rating %>
          <% if packet.packet_ratings.where(user: current_user).empty? %>
              <%= link_to packet_packet_ratings_path(packet), method: :post, remote: true do %>
                  <span style="font-size: 3rem;">
                    <span style="color: #6dde89;">
                      <i class=" icon fas fa-heart"></i>
                    </span>
                  </span>
              <% end %>
          <% end %>
          </div>
          <div class = "packet-avatar">
            <% if packet.user.photo.attached? %>
              <%= cl_image_tag packet.user.photo.key, class: "avatar-large dropdown-toggle", id:"navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <a class = "no-avatar-icon" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span style="font-size: 58px;">
                  <span style="color: #6dde89;">
                    <i class="fas fa-plus-circle"></i>
                  </span>
                </span>
              </a>
            <% end %>
            <div class="dropdown-menu dropdown-menu-right diwise-dropdown" aria-labelledby="navbarDropdown">
              <%= link_to "See #{packet.user.username}'s profile", user_path( packet.user_id), class: "dropdown-item" %>
              <%= link_to "Start a conversation with #{packet.user.username}", packet_chatrooms_path(packet), method: :post, class: "dropdown-item", remote: true %>
            </div>
          </div>
          </div>
        <% end %>
        </div>
      </div>
      <div id="projects" class="tab-pane fade">
        <div class="d-flex justify-content-between mb-5 projects-container">
          <%= link_to "+Add a new project!", new_project_path, class: "btn btn-primary btn-md btn-rounded btn-open-card text-center"%>
          <% if @user.projects.exists? %>
            <h2 class="text-center mb-2">Your Active Projects</h2>
          <% else %>
            <h2 class="text-center mb-2">No Active Projects</h2>
          <% end %>
        </div>
        <div class="container d-flex justify-content-between">
          <div class="cards">
            <% @user.projects.each do |project| %>
              <div class="card shadow">
                <div class="background-image-card" style="background-image: url(<%= image_path @sample_image.sample %>);">
                  <p class="card-title font-weight-bold"><%= project.title.capitalize %></p>
                </div>
                <div class="card-body">
                  <div class="d-flex pt-3 pb-3 justify-content-between align-items-center">
                    <%= link_to "Open", project_path(project), class: "btn btn-primary btn-md btn-rounded btn-open-card" %>
                    <%= link_to project_path(project), data: { confirm: "Are you sure?" }, method: :delete do %>
                      <i class="fas fa-trash-alt"></i>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <div id="settings" class="tab-pane fade">
        <h3>Settings</h3>
        <p>Eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
      </div>
    </div>
  </div>
</div>