config/routes.rb
Rails.application.routes.draw do
  get 'categories/show'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :packets, only: [:new, :create, :index, :show, :destroy] do
    resources :packet_ratings, only: [:create] # upvote
    resources :project_packets, only: [:create]
    resources :packet_tools, only: [:create]
    resources :chatrooms, only: [:create]
  end
  resources :chatrooms, only: [:show, :destroy] do
    resources :messages, only: [:create]
  end

  resources :users, only: [:show]
  resources :projects, only: [:new, :create, :show, :destroy]
  resources :categories, only: [:show]

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer d-flex justify-content-center text-center">
  <div class="social">
    <a href="#"><i class="fab fa-facebook-f"></i></a>
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a><br>
    <p>This website was coded with <i class="fas fa-heart"></i> at DI-WISE</p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-dark navbar-diwise" style="background-color:#202C31;" >
  <!-- Logo -->
  <div class= "nav-item">
    <%= link_to root_path, class: "navbar-brand" do %>
      <strong>DI-WISE</strong>
  <% end %>

  <!-- Search Form -->
    <div class="search-form-control form-group">
      <%= form_tag packets_path, method: :get do %>
        <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "What are you looking for?" %>
        <%= button_tag "Search", class: "btn search-btn" do %><i class="fa fa-search"></i><% end %>
      <% end %>
    </div>
  </div>

  <!-- Nav Buttons -->
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class = "navbar-nav">

      <!-- Categories Dropdown -->
      <li class= "nav-item dropdown mx-3">
        <a class="top-nav" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categories</a>
          <div class="dropdown-menu dropdown-menu-right diwise-dropdown" aria-labelledby="navbarDropdown">
            <% Category.all.each do |category| %>
              <%= link_to category.name, category_path(category), class: "dropdown-item" %>
            <% end %>
          </div>
      </li>

  <!-- All -->
      <li class="nav-item active mx-3">
        <%= link_to "Browse All Lessons", packets_path, class: "top-nav" %>
      </li>

  <!-- User Dropdown -->
      <% if user_signed_in? %>
        <li class="nav-item dropdown ml-3">
        <% if current_user.photo.attached? %>
          <%= cl_image_tag current_user.photo.key, class: "avatar-bordered dropdown-toggle", id:"navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
          <a id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span style="font-size: 2rem;">
              <span style="color: #6dde89;">
                <i class="fas fa-plus-circle"></i>
              </span>
            </span>
          </a>
        <% end %>
        <div class="dropdown-menu dropdown-menu-right diwise-dropdown" aria-labelledby="navbarDropdown">
          <%= link_to "My Account", user_path(current_user), class: "dropdown-item" %>
          <%= link_to "Add DIY Lesson", new_packet_path, class: "btn btn-warning", class: "dropdown-item" %>
          <%= link_to "Sign out", destroy_user_session_path, :method => :delete, class: "dropdown-item" %>
        </div>
        </li>
      <% else %>
        <li class="nav-item mr-3">
          <a><%= link_to "Login", new_user_session_path, class: "top-nav" %></a>
        </li>
        <li class="nav-item">
          <a><%= link_to "Sign Up", new_user_registration_path, class: "top-nav"%></a>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_packet_card.html.erb
<% @packets.each do |packet| %>
  <div class="card diwise-card">
    <% if packet.user == current_user %>
      <%= link_to packet_path(packet), data: { confirm: "Are you sure?" }, method: :delete do %>
        <i class="fas fa-times-circle" id="delete-icon"></i>
      <% end %>
    <% end %>
    <%= link_to packet_path(packet) do %>
      <div class ="px-3 pt-3 mt-2">
        <% if packet.photos.any? %>
          <%= cl_image_tag packet.photos.first.key, class: "card-img-top w-100" %>
        <% elsif packet.youtube_url.present? %>
          <iframe height='250px' class = "w-100 "src="https://www.youtube.com/embed/<%= packet.youtube_url %>"></iframe>
        <% end %>
      </div>
    <% end %>
    <div class="container">
      <%= link_to packet_path(packet) do %>
        <h4 class="card-title pr-3 my-3 packet-title" id="title-packet-index"><%= packet.title %></h4>
      <% end %>
      <%= link_to category_path(packet.category) do %>
        <p class= "card-text pr-3 packet-title" id="link-category"><%= packet.category&.name %></p>
      <% end %>
    </div>
    <div class=" d-flex container container-rating align-items-center justify-content-center" id="packet-<%= packet.id %>">
      <%= packet.rating %>
      <% if packet.packet_ratings.where(user: current_user).empty? %>
        <%= link_to packet_packet_ratings_path(packet), method: :post, remote: true do %>
          <span style="font-size: 3rem;">
            <span style="color: #6dde89;">
              <i class=" icon fas fa-heart"></i>
            </span>
          </span>
        <% end %>
      <% end %>
    </div>
    <div class = "packet-avatar">
      <% if packet.user.photo.attached? %>
        <%= cl_image_tag packet.user.photo.key, class: "avatar-large dropdown-toggle", id:"navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      <% else %>
        <a class = "no-avatar-icon" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span style="font-size: 58px;">
            <span style="color: #6dde89;">
              <i class="fas fa-plus-circle"></i>
            </span>
          </span>
        </a>
      <% end %>
      <div class="dropdown-menu dropdown-menu-right diwise-dropdown" aria-labelledby="navbarDropdown">
        <%= link_to "See #{packet.user.username}'s profile", user_path( packet.user_id), class: "dropdown-item" %>
        <%= link_to "Start a conversation with #{packet.user.username}", packet_chatrooms_path(packet), method: :post, class: "dropdown-item", remote: true %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_tool_card.html.erb
<div class="tool-cards-grid">
  <% @packet.tools.each do |tool| %>
	<div class = "card tool-card ">
	   <div class="container d-flex flex-column align-items-center py-2">
	   	<span class="tool-circle"><i class="<%= tool.icon_image %> tool-icon"></i></span>
	   <strong><%= tool.name %></strong>
	   </div>
	</div>
  <% end %> 	
</div>